-- write your queries underneath each number:
 
-- 1. the total number of rows in the database
-- 2. show the first 15 rows, but only display 3 columns (your choice)
-- 3. do the same as above, but chose a column to sort on, and sort in descending order
-- 4. add a new column without a default value
-- 5. set the value of that new column
-- 6. show only the unique (non duplicates) of a column of your choice
-- 7.group rows together by a column value (your choice) and use an aggregate function to calculate something about that group 
-- 8. now, using the same grouping query or creating another one, find a way to filter the query results based on the values for the groups 
-- 9. write a comment about your query 9
-- 10. write a comment about your query 10
-- 11. write a comment about your query 11
-- 12. write a comment about your query 12
